function [deadTimeUs, metric, sweep] = calibrateZteDeadTime(fids, ddw, gr, rj, deadTimeUs0, ...
    kLocations, effMtx, np, fullEcho, params, maxSpokes, reporter)

% Calibrate the ZTE dead time by reconstructing across a range of values
%
%   [deadTimeUs, metric, sweep] = proud.reco.calibrateZteDeadTime(fids, ddw, gr, rj, ...
%       deadTimeUs0, kLocations, effMtx, np, fullEcho, params, maxSpokes, reporter)
%
%   fids         nFid x nSpokes complex FIDs for one coil, one echo, one dynamic
%   ddw          dwell time, s
%   gr           readout gradient, G/cm
%   rj           1 x np sample positions along the spoke, cm
%   deadTimeUs0  current value, us; kept if the sweep does not find a peak
%   kLocations   3 x nSamples x nSpokes trajectory, as the reconstruction builds it
%   effMtx       gridding matrix, 2*np in the reconstruction
%   np           reconstructed matrix along one axis
%   fullEcho     obj.fullEchoZTE
%   params       reconstruction parameters, for the readout filter and sdc3_MAT
%   maxSpokes    spokes to calibrate on; the set is thinned to this many
%   reporter     optional proud.Reporter
%
%   metric, sweep  the curve that was maximised and the dead times it was
%                  evaluated at, for inspection
%
% The dead time is scored on the reconstructed image, not on the FIDs. An
% algebraic criterion was tried first -- minimise the least-squares residual of
% E*rho = [conj(flipud(fid)); fid] over the dead time -- and it does recover the
% right answer from simulated FIDs. On real data it fails completely: the
% residual falls monotonically from 0 to 40 us with no minimum, because a larger
% dead time gives E faster phase ramps and so a more flexible basis, and real
% FIDs never fit the model exactly. The criterion rewards fitting power rather
% than correctness. Simulated FIDs hide this because they are generated by the
% same operator the reconstruction inverts.
%
% What the image does instead is unambiguous, and visible: too little dead time
% leaves ringing and dark-band artefacts, too much blurs the volume towards a
% featureless blob. The score used here is the entropy of the normalised
% magnitude image,
%
%     a = |image|^2 / sum(|image|^2),   H = -sum(a .* log(a)),
%
% and it is MAXIMISED, which is the opposite of the usual autofocus convention.
% That is not a sign error. Both ends of the range concentrate the image energy
% -- into artefacts at short dead times, into a central blob at long ones -- so
% entropy is low at both, and peaks where the anatomy is spread out and detailed.
% Minimising it would pick the blurriest reconstruction available.
%
% Measured on ten ZTE datasets, this peak and the peak of an L1/L2 sparsity
% score agree to about 1 us on every one, and the peak sits where the images are
% visibly sharpest. Note that the optimum tracks the matrix size -- about 8 to
% 10 us at np = 64 and 12 to 16 us at np = 128 -- so it is a sharpness against
% artefact trade-off for the reconstruction at hand, not a measurement of the
% receiver hardware constant.
%
% One gridding pass per candidate makes this expensive, so it runs on an
% undersampled copy: the spokes are thinned to maxSpokes and the density
% compensation is recomputed once for the thinned set, outside the loop. Every
% candidate is undersampled the same way and only the comparison between them is
% used. Only the first echo and the first dynamic of one coil are passed in.
%
% Gustav Strijkers
% g.j.strijkers@amsterdamumc.nl
% August 2026

    if nargin < 12 || isempty(reporter)
        reporter = proud.Reporter();
    end
    if nargin < 11 || isempty(maxSpokes)
        maxSpokes = 1000;
    end

    deadTimeUs = deadTimeUs0;
    metric = [];
    sweep = [];

    gam = proud.util.gyro('H1','rad/Gs');
    rj = rj(:).';

    [nFid, nSpokes] = size(fids);
    if nFid < 8 || nSpokes < 1
        return
    end

    % Pad to the length the reconstruction inverts
    if nFid < np
        fids = [fids; zeros(np-nFid, nSpokes)];
    end
    nFit = size(fids,1);

    % Thin the spokes to keep one gridding pass affordable. Take them evenly
    % across the acquisition so the thinned set still covers the sphere.
    if nSpokes > maxSpokes
        keep = unique(round(linspace(1, nSpokes, maxSpokes)));
        fids = fids(:,keep);
        kLocations = kLocations(:,:,keep);
        reporter.message(strcat("Calibrating ZTE dead time on ", num2str(numel(keep)), ...
            " of ", num2str(nSpokes), " spokes ..."));
        nSpokes = numel(keep);
    end

    % Density compensation for the thinned set, once, outside the sweep. The
    % full-set DCF would be wrong here: fewer spokes is a lower sample density.
    pre = sdc3_MAT(kLocations, params.sdcIterInitial, effMtx, 0, params.sdcOsfInitial);
    DCF = sdc3_MAT(kLocations, params.sdcIterFinal, effMtx, 0, params.sdcOsfFinal, pre);

    % Same readout filter the reconstruction applies to its stacked FID
    tukFilter = tukeywin(2*nFit, 2*params.tukeyFilterWidth);
    D = [conj(flipud(fids)); fids].*tukFilter;

    % The window is set in dwell times rather than around the entered value: the
    % optimum has been seen between about 1.5 and 3.5 dwells across matrix sizes,
    % and the entered value is not a reliable starting point for it.
    ddwUs = ddw*1e6;
    lo = 0.5*ddwUs;
    hi = 4.5*ddwUs;
    nSweep = 17;
    sweep = linspace(lo, hi, nSweep);
    step = sweep(2) - sweep(1);
    metric = zeros(1, nSweep);

    reporter.message(strcat("Sweeping ZTE dead time over ", num2str(lo,'%.1f'), ...
        " to ", num2str(hi,'%.1f'), " us, ", num2str(nSweep), " reconstructions ..."));

    n = (0:nFit-1)';

    for k = 1:nSweep

        if reporter.aborted('reco')
            return
        end

        % Recover the projections exactly as the reconstruction does
        ph = gam*(sweep(k)*1e-6 + n*ddw)*gr*rj;
        E = [flipud(exp(-1i*ph)); exp(+1i*ph)];
        projs = pinv(E)*D;

        % Projections to spoke k-space, keeping the half the gridder expects
        echo = fftshift(fft(ifftshift(projs,1),[],1),1);
        if ~fullEcho
            echo = echo(round(np/2)+1:end,:);
        end

        % Grid and transform, the non-iterative branch of the reconstruction
        recoFid = zeros([size(echo,1) nSpokes 2]);
        recoFid(:,:,1) = real(echo);
        recoFid(:,:,2) = imag(echo);

        gData = grid3_MAT_nt(permute(recoFid,[3 1 2]), kLocations, DCF, effMtx, ...
            params.sdcNumThreads, 0);
        gData = squeeze(gData(1,:,:,:) + 1j*gData(2,:,:,:));
        gData = ifftshift(ifftn(ifftshift(gData)));
        image = gData(end/2 + (-np/2:np/2-1), end/2 + (-np/2:np/2-1), end/2 + (-np/2:np/2-1));

        metric(k) = imageEntropy(image);

        reporter.advance();
        reporter.showProgress();
        drawnow;

    end

    [~, k] = max(metric);

    % A peak on the edge of the window is not a peak
    if k == 1 || k == nSweep
        reporter.message("WARNING: ZTE dead time ran to the edge of the sweep, keeping the entered value ...", 1);
        reporter.status(1);
        deadTimeUs = deadTimeUs0;
        return
    end

    % A flat curve means the image does not respond to the dead time
    contrast = (max(metric) - min(metric))/max(metric);
    if contrast < 1e-3
        reporter.message("WARNING: ZTE dead time barely changes the image, keeping the entered value ...", 1);
        reporter.status(1);
        deadTimeUs = deadTimeUs0;
        return
    end

    % Parabola through the peak and its neighbours, for sub-step precision
    y1 = metric(k-1); y2 = metric(k); y3 = metric(k+1);
    den = y1 - 2*y2 + y3;
    if den < 0
        deadTimeUs = sweep(k) + 0.5*step*(y1 - y3)/den;
    else
        deadTimeUs = sweep(k);
    end

    reporter.message(strcat("ZTE dead time = ", num2str(deadTimeUs,'%.2f'), ...
        " us (entered ", num2str(deadTimeUs0,'%.2f'), ") ..."));

end % calibrateZteDeadTime


% ---------------------------------------------------------------------------------
% Entropy of the normalised magnitude image; the maximum is the sharpest image
% ---------------------------------------------------------------------------------
function h = imageEntropy(image)

    a = abs(image(:)).^2;
    s = sum(a);
    if s <= 0
        h = 0;
        return
    end
    a = a/s;
    a = a(a > 0);
    h = -sum(a.*log(a));

end % imageEntropy
